---
abstract: 'CPAN source list data aggregator.'
author:
  - 'Yo-An Lin <cornelius.howl {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Source
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Any::Moose: 0
  CPAN::DistnameInfo: 0
  Cache::File: 0
  Compress::Zlib: 0
  DateTime: 0
  DateTime::Format::HTTP: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  Mouse: 0
  Try::Tiny: 0
  URI: 0
  XML::Simple: 0
  YAML: 0
  YAML::XS: 0
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.corneltek.com/perl/CPAN-Source.git
version: 0.03
